name: 'Auto-close marked issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been closed due to inactivity in over 30 days after being marked for closure.'
          stale-pr-message: 'This pull request has been closed due to inactivity in over 30 days after being marked for closure.'
          days-before-stale: 7
          days-before-close: 60
          stale-issue-label: 'Stale ğŸš®'
          exempt-issue-labels: 'ğŸš¨ Help Wanted ğŸš¨, Note to self âœï¸ğŸ—’, Pending ğŸ“Œ, ...in progress ğŸš§'
          stale-pr-label: 'Stale ğŸš®'
          exempt-pr-labels: 'Bug Fix ğŸ‘‹ğŸğŸ’¥, ğŸš¨ Help Wanted ğŸš¨, ...in progress ğŸš§, â¤´ï¸ Rebase Needed â¤´ï¸'
